# Generated by Django 5.2 on 2025-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_content', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
